version: '3.1'
services:
  main:
    build: ewm-main
    image: ewm-main
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 128M
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - SPRING_DATASOURCE_URL=${MAIN_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${MAIN_DATASOURCE_USER}
      - SPRING_DATASOURCE_PASSWORD=${MAIN_DATASOURCE_PASSWORD}
      - STATS_SERVICE_URL=${STATS_SERVICE_URL}
    networks:
      - ewm-net

  main-db:
    image: postgres:14-alpine
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 128M
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=${MAIN_POSTGRES_DB}
      - POSTGRES_USER=${MAIN_POSTGRES_USER}
      - POSTGRES_PASSWORD=${MAIN_POSTGRES_PASSWORD}
    networks:
      - ewm-net

  stats-service:
    build: ewm-stats/ewm-stats-service
    image: ewm-stats-service
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 128M
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=${STATS_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${STATS_DATASOURCE_USER}
      - SPRING_DATASOURCE_PASSWORD=${STATS_DATASOURCE_PASSWORD}
    networks:
      - ewm-net

  stats-db:
    image: postgres:14-alpine
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 128M
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=${STATS_POSTGRES_DB}
      - POSTGRES_USER=${STATS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${STATS_POSTGRES_PASSWORD}
    networks:
      - ewm-net

networks:
  ewm-net:
    driver: bridge