version: '3.1'
services:
  stats-service:
    build: ewm-stats/ewm-stats-service
    image: ewm-stats-service
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/EwmStatsDb
      - SPRING_DATASOURCE_USERNAME=EwmDbAdmin
      - SPRING_DATASOURCE_PASSWORD=admin

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=EwmStatsDb
      - POSTGRES_USER=EwmDbAdmin
      - POSTGRES_PASSWORD=admin

