server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${MAIN_DATASOURCE_URL}
    username: ${MAIN_DATASOURCE_USER}
    password: ${MAIN_DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            - INFO
            - JpaTransactionManager: DEBUG
        transaction:
          - INFO
          - interceptor: TRACE
ewm-stats-service:
  url: ${STATS_SERVICE_URL}



