server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/EmwStatsDb
    username: EmwStatsDbAdmin
    password: admin
logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            - INFO
            - JpaTransactionManager: DEBUG
        transaction:
          - INFO
          - interceptor: TRACE



