server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${STATS_DATASOURCE_URL}
    username: ${STATS_DATASOURCE_USER}
    password: ${STATS_DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            - INFO
            - JpaTransactionManager: DEBUG
        transaction:
          - INFO
          - interceptor: TRACE



